version: "3"
services: 
  web:
    build: .
    volumes:
      - .:/dockerpro
    ports:
      - 8000:8000
    image: web:dockerpro
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
